# Generated by Django 4.1.2 on 2022-11-05 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridgeUS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='weight',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='rating',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='star',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='type',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='shopitemdetail',
            name='color',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='shopitemdetail',
            name='left_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='shopitemdetail',
            name='size',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='usershop',
            name='cart',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='usershop',
            name='credit',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='usershop',
            name='favorite_clothes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='usershop',
            name='purchased_item',
            field=models.TextField(null=True),
        ),
    ]
