# Generated by Django 4.1.2 on 2022-11-05 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridgeUS', '0002_alter_comment_content_alter_customuser_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nickname',
            field=models.TextField(null=True),
        ),
    ]
