# Generated by Django 4.1.2 on 2022-11-05 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bridgeUS', '0003_customuser_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bridgeUS.shopitem'),
        ),
    ]
