# Generated by Django 4.1.2 on 2022-11-05 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridgeUS', '0005_userorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
