# Generated by Django 4.1.2 on 2022-11-07 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bridgeUS', '0008_review_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userorder',
            old_name='orderd_item',
            new_name='ordered_item',
        ),
    ]
