# Generated by Django 4.1.2 on 2022-11-08 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridgeUS', '0009_rename_orderd_item_userorder_ordered_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='likes',
            field=models.IntegerField(null=True),
        ),
    ]
