# Generated by Django 4.1.3 on 2022-11-09 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bridgeUS", "0010_review_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="image_url",
            field=models.TextField(null=True),
        ),
    ]
