# Generated by Django 4.1.3 on 2022-11-12 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridgeUS', '0011_review_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopitem',
            name='star',
        ),
        migrations.RemoveField(
            model_name='usershop',
            name='favorite_clothes',
        ),
        migrations.AlterField(
            model_name='usershop',
            name='cart',
            field=models.JSONField(null=True),
        ),
    ]
