# Generated by Django 4.1.3 on 2022-11-12 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridgeUS', '0012_remove_shopitem_star_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='color',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='userorder',
            name='ordered_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userorder',
            name='size',
            field=models.TextField(null=True),
        ),
    ]
