# Generated by Django 4.1.3 on 2022-11-19 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridgeUS', '0014_shopitem_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='fast_shipping',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='order_status',
            field=models.IntegerField(null=True),
        ),
    ]
