# Generated by Django 4.1.3 on 2022-11-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridgeUS', '0015_userorder_fast_shipping_alter_userorder_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usershop',
            name='purchased_item',
            field=models.JSONField(null=True),
        ),
    ]
