# Generated by Django 4.1.3 on 2022-11-19 07:08

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('bridgeUS', '0016_alter_usershop_purchased_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopitem',
            name='tag',
        ),
        migrations.AddField(
            model_name='shopitem',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
