# Generated by Django 4.1.3 on 2022-11-19 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bridgeUS", "0017_review_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="image",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
    ]
