# Generated by Django 4.1.3 on 2022-11-19 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bridgeUS", "0017_remove_shopitem_tag_shopitem_tags"),
        ("bridgeUS", "0018_alter_review_image"),
    ]

    operations = []
