# Generated by Django 4.1.3 on 2022-11-19 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bridgeUS', '0019_merge_20221119_0806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='image_url',
        ),
    ]
