# Generated by Django 4.1.3 on 2022-11-26 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridgeUS', '0020_remove_review_image_url_remove_shopitem_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='raters',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='likes',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=5, null=True),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='price',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='rating',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='shopitemdetail',
            name='left_amount',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='ordered_amount',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='usershop',
            name='credit',
            field=models.FloatField(default=0, null=True),
        ),
    ]
