# Generated by Django 4.1.3 on 2022-11-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridgeUS', '0021_shopitem_raters_alter_review_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='liked_posts',
            field=models.TextField(default='', null=True),
        ),
    ]
