# Generated by Django 4.1.3 on 2022-11-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bridgeUS", "0022_customuser_liked_posts"),
    ]

    operations = [
        migrations.AddField(
            model_name="userorder",
            name="single_price",
            field=models.IntegerField(null=True),
        ),
    ]
