# Generated by Django 4.1.3 on 2022-12-13 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bridgeUS", "0023_userorder_single_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usershop",
            name="credit",
            field=models.FloatField(default=10000, null=True),
        ),
    ]
